## -*- docker-image-name: "anshulverma/kaksha" -*-

FROM anshulverma/baseimage

MAINTAINER anshul.verma86@gmail.com

USER root

RUN ["useradd", "-m", "anshul"]

USER anshul

ENV HOME /home/anshul

# Default command
CMD ["bash"]
